# Generated by Django 4.2.2 on 2023-06-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_remove_city_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
    ]
